# Setup
title:            Nicole's IDH Blog
tagline:          'Exploring Digital Humanities'
description:      'Created for Intro to DH, a Grad course at _Northeastern University_, Fall 2020'
url:              https://sojkowski.github.io
baseurl:          '/IDH-blog/'
paginate:         5

# About and contact
author:
  name:           'Nicole Sojkowski'
  url:            'https://www.linkedin.com/in/nicole-sojkowski-808748129/'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
